version: '3'
name: remind-me-app
networks:
  laravel:
services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached
            - /var/www/vendor/
        networks:
            - laravel
    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx
        ports:
            - 8081:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        networks:
            - laravel

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    db:
        image: mysql:8.1
        ports:
            - 3308:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: remind_me_app
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        networks:
            - laravel

    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8082:80
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        volumes:
            - .docker/phpmyadmin/sessions:/sessions

    ####################################################################################################
    # Mailpit
    ####################################################################################################
    # mail:
    #     image: axllent/mailpit:latest
    #     ports:
    #     - 8025:8025
    #     - 1025:1025
    app-react:
      build: 
        context: ./react
        dockerfile: Dockerfile
      volumes:
        - ./react:/app
        - /app/node_modules
        - /app/.next
      restart: always
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
      ports:
        - "3000:3000"

